/// Flutter icons FileIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FileIcon
///      fonts:
///       - asset: fonts/FileIcon.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FileIcon {
  FileIcon._();

  static const _kFontFam = 'FileIcon';
  static const String? _kFontPkg = null;

  static const IconData doc_text =
      IconData(0xf0f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_pdf =
      IconData(0xf1c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_word =
      IconData(0xf1c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_excel =
      IconData(0xf1c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_powerpoint =
      IconData(0xf1c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_image =
      IconData(0xf1c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_archive =
      IconData(0xf1c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
